export interface ProjectData {
  id: string
  slug: string
  title: string
  tagline: string
  role: string
  timeline: string
  category: string
  icon: string
  accent: string
  shortDescription: string
  outcome: string
  tags: string[]
  /** Hero image for the portfolio gallery — path under `public/` (e.g. `/images/projects/{slug}.jpg`). */
  coverImage: string
  coverImageAlt: string
  span?: string
  minH?: string
  impactMetrics: {
    value: string
    label: string
  }[]
  problem: string
  myRole: string
  solution: string
  processSteps?: {
    phase: string
    description: string
  }[]
  metrics: string[]
  keyLearning?: string
  techStack: {
    category: string
    technologies: string[]
  }[]
  /** IDs of services this project demonstrates (see `services-data.ts`). */
  relatedServiceIds?: string[]
  /** IDs of testimonials that reference this project or its outcomes (see `testimonials-data.ts`). */
  relatedTestimonialIds?: string[]
  /** `tag` values from proof metrics that this project evidences (see `proof-metrics-data.ts`). */
  relatedProofMetricTags?: string[]
  /** Step IDs from the "how I work" phases (e.g. "01" Discover – "06" Value) emphasised on this project. */
  relatedPhaseSteps?: string[]
  /** Slugs of 1–2 sibling projects in the same theme, for cross-navigation. */
  relatedProjectSlugs?: string[]
}

export const projects: ProjectData[] = [
  {
    id: "1",
    slug: "fraud-detection-engine",
    title: "AI-Powered Fraud Detection Engine",
    tagline: "Reduced false positives by 87% while catching 98% of fraud in real time — protecting $12M+ annually.",
    role: "Lead Technical Business Analyst — AML & Compliance",
    timeline: "Q1–Q2 2023 · 5 months",
    category: "AI/ML + Compliance",
    icon: "🚨",
    accent: "bg-red-500/15 text-red-600",
    shortDescription: "Real-time anomaly detection system using deep learning to flag suspicious transactions with 99.2% accuracy.",
    outcome: "99.2% accuracy",
    tags: ["AML", "Compliance", "Requirements", "SQL", "JIRA"],
    coverImage: "/images/projects/fraud-detection-engine.jpg",
    coverImageAlt:
      "Code and data on a developer screen, suggesting fraud analysis and real-time detection systems.",
    span: "md:col-span-8",
    minH: "min-h-[300px] md:min-h-[340px]",
    impactMetrics: [
      { value: "99.2%", label: "detection accuracy" },
      { value: "87%", label: "fewer false positives" },
      { value: "$12M+", label: "fraud prevented annually" },
      { value: "<100ms", label: "detection latency" },
    ],
    problem: "Legacy fraud detection relied on rule-based systems with ~85% accuracy and 2-3 hour detection latency. Rules-based systems generated 40% false positives, causing customer friction. Banks needed real-time detection with minimal false positives.",
    myRole: "I led the requirements definition and stakeholder alignment for this fraud detection initiative. Working between compliance officers and the engineering team, I audited every existing rule set, interviewed AML analysts to map false-positive failure modes, and authored the functional specification that guided model development. I designed the UAT framework used to validate detection thresholds against live transaction samples and ran structured sessions with compliance leadership to define the precision/recall tradeoffs that balanced fraud capture with customer friction before cutover.",
    solution: "Built a multi-model ensemble combining LSTM neural networks for behavioral patterns, XGBoost for transaction features, and graph neural networks for ring detection. Implemented streaming pipeline using Kafka for sub-100ms latency. Model retrained daily on new transaction patterns.",
    processSteps: [
      { phase: "Discovery", description: "Audited existing rule sets and interviewed compliance analysts to map false-positive failure modes." },
      { phase: "Requirements", description: "Translated compliance requirements into functional specifications for the model development team, including precision/recall thresholds and explainability standards." },
      { phase: "UAT Design", description: "Built a structured UAT framework using historical transaction samples to validate detection accuracy before shadow-run began." },
      { phase: "Cutover", description: "Managed stakeholder sign-off across compliance, operations, and product during the 4-week parallel-run period before full cutover." },
    ],
    metrics: [
      "99.2% detection accuracy (up from 85%)",
      "87% reduction in false positives (40% → 5%)",
      "98% of fraud caught within 2 minutes",
      "$12M+ in fraud prevented annually",
      "Scales to 10M+ transactions per day",
    ],
    keyLearning: "The compliance team's precise definition of 'acceptable false positive rate' — worked out in stakeholder workshops before a single model was trained — was the single most important upstream decision. Ambiguity in that threshold would have caused every downstream technical choice to be revisited at go-live.",
    techStack: [
      { category: "ML/AI", technologies: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "XGBoost"] },
      { category: "Data Pipeline", technologies: ["Apache Kafka", "Apache Spark", "PostgreSQL"] },
      { category: "Infrastructure", technologies: ["Kubernetes", "Docker", "Redis"] },
      { category: "Monitoring", technologies: ["Prometheus", "Grafana", "ELK Stack"] },
    ],
    relatedServiceIds: ["ai-native-ux"],
    relatedTestimonialIds: ["t2"],
    relatedPhaseSteps: ["01", "02", "04"],
    relatedProjectSlugs: ["kyc-aml-automation", "compliance-risk-monitoring"],
  },
  {
    id: "2",
    slug: "payment-settlement-platform",
    title: "Payment Gateway Migration & Settlement Platform",
    tagline: "Migrated enterprise payment infrastructure to modern SaaS — saving $1M+ and eliminating reconciliation delays.",
    role: "Lead Business Systems Analyst",
    timeline: "Q4 2023–Q2 2024 · 5 months",
    category: "Payments + Enterprise Systems",
    icon: "⚡",
    accent: "bg-yellow-500/15 text-yellow-600",
    shortDescription: "End-to-end business analysis and migration planning for a payment gateway transition. Delivered $1M+ in savings through vendor consolidation and streamlined settlement workflows.",
    outcome: "$1M+ saved",
    tags: ["Salesforce", "SAP", "MuleSoft", "Payment Gateways", "SQL"],
    coverImage: "/images/projects/payment-settlement-platform.jpg",
    coverImageAlt: "Hands using a smartphone for a digital payment, suggesting instant settlement flows.",
    span: "md:col-span-8",
    minH: "min-h-[300px] md:min-h-[340px]",
    impactMetrics: [
      { value: "$1M+", label: "cost savings through migration" },
      { value: "30%", label: "reduction in time-to-deploy" },
      { value: "100%", label: "transaction integrity maintained" },
      { value: "5", label: "globally distributed teams aligned" },
    ],
    problem: "Legacy payment gateway infrastructure was creating $1M+ in annual vendor costs, with reconciliation processes that took days and introduced errors. Multiple disconnected finance and operations systems had no single source of truth for settlement status.",
    myRole: "I led the end-to-end business analysis for this payment gateway migration from a legacy vendor to a modern SaaS platform. I elicited requirements across finance, operations, compliance, and engineering stakeholders across five globally distributed teams, performed comprehensive data profiling of the existing payment transaction records, and documented source-to-target mapping for all settlement data flows. I authored the integration specification for the new payment gateway, coordinated vendor engagement, and designed the UAT framework that validated transaction integrity before cutover. The migration delivered $1M+ in savings by eliminating the legacy vendor contract.",
    solution: "Structured requirements-led migration: current-state audit, stakeholder alignment across five teams, data profiling and cleansing, source-to-target mapping, integration specifications, and a phased cutover with dual-write validation to guarantee 100% transaction integrity.",
    processSteps: [
      { phase: "Discovery", description: "Audited existing payment workflows, mapped all integration touchpoints across finance, operations, and compliance, and identified gaps in the current reconciliation process." },
      { phase: "Requirements", description: "Facilitated workshops with 100+ stakeholders to define the future-state settlement workflow and integration requirements for the new payment gateway." },
      { phase: "Data Mapping", description: "Performed data profiling on legacy transaction records, documented source-to-target mapping, and defined cleansing and transformation rules." },
      { phase: "Migration", description: "Managed phased cutover with dual-write validation period, tracking reconciliation results between old and new systems before full transition." },
    ],
    metrics: [
      "$1M+ in annual cost savings through vendor consolidation",
      "30% reduction in time-to-deploy for enterprise solutions",
      "100% transaction integrity maintained across migration",
      "Reconciliation cycle reduced from days to real-time",
      "Zero post-migration audit exceptions",
    ],
    keyLearning: "The most critical risk in any payment migration is the edge cases that only surface under real transaction volumes — retroactive adjustments, split settlements, currency conversions. Identifying and documenting these explicitly in the requirements phase, rather than discovering them in UAT, was what kept the cutover clean.",
    techStack: [
      { category: "Platforms", technologies: ["Salesforce", "SAP", "Zuora", "MuleSoft"] },
      { category: "Analysis", technologies: ["SQL", "SSMS", "Excel", "Confluence"] },
      { category: "Integration", technologies: ["RESTful APIs", "SOAP", "ETL/ELT"] },
      { category: "Project Tools", technologies: ["JIRA", "SharePoint", "Visio"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t2"],
    relatedProofMetricTags: ["Platform consolidation"],
    relatedPhaseSteps: ["02", "03", "04"],
    relatedProjectSlugs: ["api-first-banking-microservices", "kyc-aml-automation"],
  },
  {
    id: "3",
    slug: "kyc-aml-automation",
    title: "KYC/AML Compliance Automation Pipeline",
    tagline: "Cut customer onboarding from 3 days to 5 minutes while maintaining regulatory accuracy across 100k+ applications.",
    role: "Lead Technical Business Analyst — Compliance",
    timeline: "Q4 2022–Q1 2023 · 4 months",
    category: "Compliance + Automation",
    icon: "🔍",
    accent: "bg-blue-500/15 text-blue-600",
    shortDescription: "End-to-end requirements and compliance analysis for KYC/AML automation at a major Canadian financial institution. Enabled onboarding in minutes while satisfying FINTRAC regulatory standards.",
    outcome: "3 days → 5 min",
    tags: ["KYC/AML", "FINTRAC", "SQL", "Compliance", "Agile"],
    coverImage: "/images/projects/kyc-aml-automation.jpg",
    coverImageAlt: "Laptop and documents on a desk, representing identity verification and compliance review.",
    span: "md:col-span-4",
    minH: "min-h-[280px] md:min-h-[340px]",
    impactMetrics: [
      { value: "5 min", label: "onboarding time (was 3 days)" },
      { value: "87%", label: "auto-approved without review" },
      { value: "99.5%", label: "data extraction accuracy" },
      { value: "92%", label: "reduction in manual review queue" },
    ],
    problem: "Manual KYC/AML processes took 2-3 days, creating poor customer experience and causing significant signup abandonment. Compliance teams manually reviewed documents with error-prone workflows that couldn't scale. FINTRAC reporting for Large Cash Transactions (LCTR), Suspicious Transaction Reporting (STR), and Electronic Funds Transfer Reporting (EFTR) required precise data attribute mapping across multiple source systems.",
    myRole: "I owned requirements analysis and compliance alignment for this KYC/AML automation initiative at a major Canadian bank. I extracted and mapped FINTRAC-specific data attributes across source systems, defined the transformation and validation rules for LCTR, STR, and EFTR reporting, and facilitated workshops with AML and compliance teams to define automated decision thresholds. I analyzed and cleansed datasets to improve data quality prior to system integration, designed the UAT framework with compliance officers to validate regulatory accuracy, and collaborated with AML stakeholders to implement robust validation and enrichment processes that met FINTRAC audit standards.",
    solution: "Requirements-led automation: FINTRAC data attribute mapping, transformation rule definition, compliance threshold workshops, data quality assessment and cleansing, and a structured UAT process run in parallel with manual review for 3 weeks before switching to automated flow.",
    processSteps: [
      { phase: "Regulatory Mapping", description: "Extracted and mapped FINTRAC-specific data attributes across source systems, defining the required capture and transformation for LCTR, STR, and EFTR." },
      { phase: "Compliance Workshops", description: "Facilitated sessions with AML and compliance teams to validate automated approval thresholds and define escalation criteria for edge cases." },
      { phase: "Data Quality", description: "Profiled, cleansed, and standardized source datasets; documented anomalies and established validation rules for source-to-target integrity." },
      { phase: "UAT & Sign-off", description: "Ran parallel manual reviews for 3 weeks, validating automated decisions against compliance officer judgements before full cutover." },
    ],
    metrics: [
      "Onboarding reduced from 3 days to under 5 minutes",
      "99.5% data extraction accuracy",
      "87% of applications auto-approved without human review",
      "92% reduction in manual review queue",
      "100k+ applications processed with zero compliance incidents",
    ],
    keyLearning: "Regulatory compliance is a data quality problem before it is a technology problem. The automation only worked because we spent the first month mapping every FINTRAC data attribute to a clean, validated source — trying to automate against dirty data would have created a compliance liability, not a solution.",
    techStack: [
      { category: "Compliance", technologies: ["FINTRAC LCTR", "STR", "EFTR", "AML"] },
      { category: "Data", technologies: ["SQL", "SSMS", "ETL", "Data Profiling"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "SharePoint", "Visio"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "Waterfall", "UAT", "BRD/TDD"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t2"],
    relatedPhaseSteps: ["01", "02", "06"],
    relatedProjectSlugs: ["fraud-detection-engine", "compliance-risk-monitoring"],
  },
  {
    id: "4",
    slug: "real-time-analytics-dashboard",
    title: "Real-time Analytics & BI Dashboard",
    tagline: "Eliminated 30-minute data lag so operations and trading teams could detect and respond to incidents in under 30 seconds.",
    role: "Lead Technical Business Analyst — BI & Reporting",
    timeline: "Q1–Q2 2021 · 4 months",
    category: "Data Engineering + Analytics",
    icon: "📊",
    accent: "bg-green-500/15 text-green-600",
    shortDescription: "Requirements definition and KPI framework design for a real-time analytics overhaul at a capital markets firm. Enabled sub-second dashboards for 100+ concurrent users across trading and operations.",
    outcome: "Sub-second latency",
    tags: ["Power BI", "Tableau", "SQL", "Salesforce", "Capital Markets"],
    coverImage: "/images/projects/real-time-analytics-dashboard.jpg",
    coverImageAlt: "Business analytics dashboard on a screen with charts and KPIs.",
    span: "md:col-span-12",
    minH: "min-h-[240px]",
    impactMetrics: [
      { value: "<1s", label: "dashboard query latency" },
      { value: "30s", label: "incident detection (was 30 min)" },
      { value: "40%", label: "faster operational decisions" },
      { value: "100+", label: "concurrent users at <200ms" },
    ],
    problem: "Legacy reporting dashboards had 30+ minute data latency. Reports were generated hourly via batch jobs. Operations and trading teams couldn't react to real-time issues — every decision was based on stale data. Business units had divergent definitions of key metrics, making cross-team reporting unreliable.",
    myRole: "I defined the reporting requirements and KPI framework for this real-time analytics overhaul at a capital markets firm. I facilitated sessions with trading desk leads, operations managers, and compliance stakeholders to document exactly what data they needed, at what latency, and in what form. I standardized metric definitions across four business units, translated those requirements into technical specifications for the data engineering team, validated the data models against source system schemas, and ran structured UAT across all business units before cutover. I also designed the custom dashboards and reports to deliver actionable insights for investment banking operations.",
    solution: "Requirements-led analytics: stakeholder workshops to define KPI taxonomy, metric standardization across business units, technical specification for pipeline and dashboard teams, source-to-target validation, and phased rollout with structured UAT.",
    metrics: [
      "Sub-second query latency on 1M+ events/sec",
      "100+ concurrent users with <200ms updates",
      "Incident detection time: 30 minutes → 30 seconds",
      "Operations team decisions 40% faster",
      "$20B+ daily transaction volume handled",
    ],
    keyLearning: "Metric standardization was the hidden prerequisite. Four business units had four different definitions of 'active client' — reconciling that ambiguity in requirements workshops, before any pipeline was built, was what made the dashboards trustworthy enough to actually change decision-making behavior.",
    techStack: [
      { category: "BI Tools", technologies: ["Tableau", "Power BI", "Salesforce Reports"] },
      { category: "Data", technologies: ["SQL", "SSMS", "Excel", "ETL"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Visio"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "UAT", "BRD", "Data Modeling"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t3"],
    relatedProofMetricTags: ["SaaS implementation"],
    relatedPhaseSteps: ["02", "03", "04"],
    relatedProjectSlugs: ["event-streaming-pipeline"],
  },
  {
    id: "5",
    slug: "event-streaming-pipeline",
    title: "Data Integration & System Decoupling Initiative",
    tagline: "Mapped and decoupled a tightly coupled platform into independently evolving domains — with 100% complete audit trails for compliance.",
    role: "Lead Technical Business Analyst — Data Architecture",
    timeline: "Q3 2021–Q1 2022 · 6 months",
    category: "Enterprise Data + Compliance",
    icon: "🌊",
    accent: "bg-indigo-500/15 text-indigo-600",
    shortDescription: "Business analysis and data flow mapping for a major platform decoupling initiative at a capital markets CRM provider. Enabled independent team delivery and compliant audit trails across 12 service domains.",
    outcome: "12 domains, 0 data loss",
    tags: ["Data Mapping", "SQL", "Salesforce", "API Integration", "Capital Markets", "Supply Chain"],
    coverImage: "/images/projects/event-streaming-pipeline.jpg",
    coverImageAlt: "Server racks in a data center, representing high-throughput event streaming.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "12", label: "service domains mapped independently" },
      { value: "100%", label: "complete compliance audit trail" },
      { value: "0", label: "data loss across all streams" },
      { value: "60%", label: "faster incident diagnosis" },
    ],
    problem: "A tightly coupled monolithic platform made it impossible to release new capabilities without coordinating across all teams. Audit trails were incomplete and unreliable. Regulatory compliance required immutable event logs that the current architecture couldn't produce.",
    myRole: "I mapped the current-state data flows across the monolithic platform, documented every inter-service dependency, and led workshops with each domain team to define their data ownership boundaries and integration contracts. I authored data mapping specifications for each of the 12 service domains, worked with the compliance team to ensure audit trail requirements were built into the data schema design from the start, and managed stakeholder sign-off across six product teams before migration began. I also coordinated with R&D and DevOps teams to translate business data requirements into technical implementation guidance.",
    solution: "Requirements-led decoupling: current-state dependency mapping, domain boundary definition workshops, data mapping documentation for each service, compliance audit trail specifications, and staged stakeholder sign-off across all affected teams.",
    metrics: [
      "12 service domains now evolve independently",
      "100% complete compliance audit trail",
      "Zero data loss across all integration streams",
      "60% faster incident diagnosis via traceable data lineage",
    ],
    keyLearning: "Defining data ownership before drawing service boundaries was the decision that prevented the most conflict. Every team disagreement during the migration traced back to unclear ownership of a shared data entity — resolving those in requirements workshops rather than in sprint planning saved weeks of rework.",
    techStack: [
      { category: "CRM", technologies: ["Salesforce", "Tier1 CRM Platform"] },
      { category: "Data", technologies: ["SQL", "SSMS", "Data Mapping", "ETL"] },
      { category: "Integration", technologies: ["RESTful APIs", "SOAP", "API Integration"] },
      { category: "Tools", technologies: ["Confluence", "JIRA", "Visio", "SharePoint"] },
    ],
    relatedTestimonialIds: ["t3"],
    relatedServiceIds: ["design-systems", "product-design-strategy"],
    relatedProofMetricTags: ["Platform consolidation"],
    relatedPhaseSteps: ["03", "04"],
    relatedProjectSlugs: ["real-time-analytics-dashboard", "api-first-banking-microservices"],
  },
  {
    id: "6",
    slug: "ai-customer-onboarding-agent",
    title: "AI-Assisted Customer Onboarding Platform",
    tagline: "87% of customers onboard without any human touch — cutting time from 3 days to 8 hours and achieving 95% satisfaction.",
    role: "Lead Technical Business Analyst — AI Implementation",
    timeline: "Q4 2023–Q1 2024 · 4 months",
    category: "AI/Agentic Systems",
    icon: "🤖",
    accent: "bg-purple-500/15 text-purple-600",
    shortDescription: "Requirements definition and process mapping for an AI-assisted onboarding initiative. Identified automation boundaries, defined UAT frameworks, and drove change management for a 87% autonomous completion rate.",
    outcome: "87% autonomous",
    tags: ["AI Implementation", "Process Mapping", "UAT", "Change Management", "JIRA"],
    coverImage: "/images/projects/ai-customer-onboarding-agent.jpg",
    coverImageAlt: "Abstract AI neural visualization suggesting autonomous agent workflows.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "87%", label: "fully autonomous completions" },
      { value: "2-8h", label: "onboarding time (was 2-3 days)" },
      { value: "95%", label: "customer satisfaction" },
      { value: "5k+", label: "onboardings processed autonomously" },
    ],
    problem: "Customer onboarding required multiple manual steps with an average time of 2-3 days. High abandonment rate due to friction. Inconsistent experience across customers. The operations team needed a clear definition of what the AI agent could decide autonomously versus what required human judgment.",
    myRole: "I led the requirements analysis and process mapping for this AI-assisted onboarding initiative. I documented every step of the existing human agent workflow using UML process models, identified which steps were strong automation candidates versus edge cases requiring human judgment, and defined the functional specifications for the AI decision boundaries. I designed the UAT shadowing protocol used to calibrate autonomous completion thresholds and ran structured change management sessions with the onboarding operations team to prepare them for the new workflow. I also defined the monitoring requirements and KPI framework for tracking autonomous completion rates post-launch.",
    solution: "Requirements-led AI implementation: end-to-end human workflow documentation, automation boundary definition, UAT shadowing design, change management programme, and monitoring KPI framework — ensuring the AI agent was built to the right specifications from the start.",
    processSteps: [
      { phase: "Workflow Mapping", description: "Documented every step a human agent performs using UML process models, identifying automation candidates versus judgment-required edge cases." },
      { phase: "Requirements", description: "Defined functional specifications for AI decision boundaries — what the system could auto-approve, re-ask for, or escalate to a human agent." },
      { phase: "UAT Design", description: "Built a shadowing protocol to run 500 test conversations and calibrate confidence thresholds for autonomous versus escalation paths." },
      { phase: "Change Management", description: "Ran structured sessions with the onboarding operations team to prepare them for the new workflow and establish feedback loops for continuous improvement." },
    ],
    metrics: [
      "2–3× faster onboarding: 2-3 days → 2-8 hours",
      "87% of customers complete without human intervention",
      "Less than 1% escalation rate",
      "95% customer satisfaction score",
      "5,000+ onboardings processed autonomously",
    ],
    keyLearning: "The hardest requirements problem was defining 'confidence' — what threshold of AI certainty justified autonomous action versus human escalation. Getting compliance, operations, and engineering aligned on that definition in a workshop, before any model was trained, was what made the production system trustworthy enough to run at 87% autonomy.",
    techStack: [
      { category: "AI Platforms", technologies: ["Claude API", "AI/LLM Integration"] },
      { category: "Process", technologies: ["UML", "Process Modeling", "Visio"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "SharePoint"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "UAT", "Change Management", "BRD"] },
    ],
    relatedServiceIds: ["ai-native-ux"],
    relatedTestimonialIds: ["t4"],
    relatedProofMetricTags: ["Change management"],
    relatedPhaseSteps: ["02", "03", "04"],
    relatedProjectSlugs: ["fraud-detection-engine", "data-breach-forensics-ai"],
  },
  {
    id: "7",
    slug: "credit-risk-underwriting",
    title: "Credit Risk Model — Requirements & Compliance",
    tagline: "Raised approval rates by 23% while simultaneously cutting default risk — translating regulatory requirements into a model the business could trust.",
    role: "Lead Technical Business Analyst — Credit & Risk",
    timeline: "Q2–Q3 2022 · 5 months",
    category: "Finance + Compliance",
    icon: "💳",
    accent: "bg-orange-500/15 text-orange-600",
    shortDescription: "End-to-end requirements and compliance analysis for a credit risk model replacing legacy rules. Translated regulatory explainability requirements into specifications the ML team could implement.",
    outcome: "23% approval uplift",
    tags: ["Credit Risk", "AML", "Compliance", "SQL", "Data Mapping"],
    coverImage: "/images/projects/credit-risk-underwriting.jpg",
    coverImageAlt: "Financial charts and trading interfaces on monitors.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "23%", label: "approval rate uplift (65% → 88%)" },
      { value: "15%", label: "reduction in default rate" },
      { value: "$15M+", label: "added annual revenue" },
      { value: "92%", label: "AUC on holdout test set" },
    ],
    problem: "Legacy rule-based credit model had 65% approval rate but a high default rate. Static rules rejected creditworthy customers and couldn't capture complex behavioral patterns. Regulators required full explainability for every credit decision — a constraint that had to be built into the model design from the start.",
    myRole: "I led requirements elicitation with credit adjudication, risk, and compliance stakeholders to define the model inputs, approval thresholds, and regulatory explainability requirements. I mapped the existing rule set to the feature engineering requirements, documented data lineage for all source attributes used in the model, and worked with compliance to ensure the explainability approach satisfied regulatory audit standards before the model was built. I ran UAT with the credit adjudication team using historical case samples and authored the operational runbook for ongoing model monitoring and governance.",
    solution: "Requirements-led model development: regulatory explainability specifications defined upfront, data lineage documentation for all 200+ features, compliance-approved threshold definition, structured UAT with historical cases, and an operational governance runbook for post-launch monitoring.",
    metrics: [
      "Approval rate improved: 65% → 88% (+23%)",
      "Default rate reduced: 8% → 6.8% (-15%)",
      "100ms prediction latency",
      "92% AUC on holdout test set",
      "$15M+ added annual revenue",
    ],
    keyLearning: "Model explainability requirements need to be defined before model design, not after. In two sessions with compliance, we uncovered that regulators required decision-level explanations in plain language — not just feature importance scores. That specification shaped the entire technical approach and would have been very expensive to retrofit.",
    techStack: [
      { category: "Compliance", technologies: ["Credit Risk", "Regulatory Reporting", "GDPR"] },
      { category: "Data", technologies: ["SQL", "SSMS", "Data Profiling", "Excel"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Visio", "SharePoint"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "UAT", "BRD/TDD", "Data Mapping"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t2"],
    relatedPhaseSteps: ["01", "02"],
    relatedProjectSlugs: ["kyc-aml-automation", "compliance-risk-monitoring"],
  },
  {
    id: "8",
    slug: "api-first-banking-microservices",
    title: "Banking Platform Modernisation — Service Decomposition",
    tagline: "Replaced a fragile monolith with 12 independently deployable domains — achieving 99.99% SLA and 10× faster deployments.",
    role: "Lead Business Systems Analyst — Platform Transformation",
    timeline: "Q4 2021–Q2 2022 · 7 months",
    category: "Enterprise Architecture + Transformation",
    icon: "🏗️",
    accent: "bg-cyan-500/15 text-cyan-600",
    shortDescription: "Business analysis and service decomposition for a major banking platform modernisation. Mapped 12 service domains, defined integration contracts, and managed cross-team stakeholder alignment across a 7-month transformation.",
    outcome: "99.99% SLA",
    tags: ["Enterprise Architecture", "API Integration", "SQL", "Salesforce", "Agile"],
    coverImage: "/images/projects/api-first-banking-microservices.jpg",
    coverImageAlt: "Rows of servers in a modern data center, suggesting cloud-native microservices.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "99.99%", label: "SLA (was 98%)" },
      { value: "10×", label: "faster feature deployments" },
      { value: "12", label: "independently deployable domains" },
      { value: "100k+", label: "concurrent users supported" },
    ],
    problem: "A monolithic banking platform was tightly coupled — one issue took down the entire system. Feature delivery required coordinating across all teams simultaneously, making velocity very slow. The organisation needed a clear map of data ownership before any technical decomposition could safely begin.",
    myRole: "I facilitated the service decomposition workshops with each product domain, documenting current-state system dependencies and defining future-state bounded contexts based on data ownership and business capability. I authored BRDs for each of the 12 service domains, managed stakeholder alignment across eight engineering and product teams, and defined the integration acceptance criteria for every service interface. I also led the data migration requirements for each service that required its own data store, ensuring traceability from business requirement to technical implementation throughout the programme.",
    solution: "Requirements-led decomposition: current-state dependency mapping, bounded context definition by data ownership, BRDs for all 12 domains, integration contract specifications, cross-team stakeholder alignment, and phased sign-off before any service was independently deployed.",
    metrics: [
      "99.99% SLA achieved (up from 98%)",
      "<50ms p99 latency on critical paths",
      "10× faster feature deployments",
      "12 services with independent deploy cadence",
      "Scales to 100k+ concurrent users",
    ],
    keyLearning: "Service decomposition succeeds or fails on data ownership, not code structure. Every cross-team conflict during the programme traced back to a database table with unclear ownership. Resolving those in requirements workshops — before any service boundaries were drawn in code — made the second half of the programme dramatically smoother.",
    techStack: [
      { category: "Platforms", technologies: ["Salesforce", "Banking APIs", "MuleSoft"] },
      { category: "Integration", technologies: ["RESTful APIs", "SOAP", "API Management"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Visio", "SharePoint"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD/TDD", "UAT", "UML"] },
    ],
    relatedServiceIds: ["design-systems"],
    relatedProofMetricTags: ["Platform consolidation"],
    relatedPhaseSteps: ["03", "04"],
    relatedProjectSlugs: ["payment-settlement-platform", "event-streaming-pipeline"],
  },
  {
    id: "9",
    slug: "compliance-risk-monitoring",
    title: "Compliance & Risk Monitoring Platform",
    tagline: "Achieved 98% money laundering detection accuracy and saved $50M+ in identified suspicious patterns — with full regulatory audit trail.",
    role: "Lead Business Systems Analyst — Compliance",
    timeline: "Q1–Q2 2024 · 5 months",
    category: "Compliance + AI",
    icon: "⚖️",
    accent: "bg-slate-500/15 text-slate-600",
    shortDescription: "Requirements definition and regulatory alignment for an AI-driven compliance monitoring platform. Translated AML requirements into detection specifications and designed the regulatory reporting data model.",
    outcome: "98% detection",
    tags: ["AML", "Compliance", "SQL", "FINTRAC", "Risk Management"],
    coverImage: "/images/projects/compliance-risk-monitoring.jpg",
    coverImageAlt: "Law books and a gavel, suggesting compliance and regulatory monitoring.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "98%", label: "detection accuracy" },
      { value: "0", label: "false positives on high-confidence alerts" },
      { value: "$50M+", label: "in suspicious patterns identified" },
      { value: "75%", label: "reduction in compliance review time" },
    ],
    problem: "Legacy AML systems flagged 40% of transactions as suspicious — an unsustainable false-positive burden on compliance teams. The organisation needed a system that compliance officers and regulators could trust, which required explainable alert reasoning alongside detection accuracy.",
    myRole: "I led requirements analysis for this compliance monitoring platform, translating AML regulatory requirements into functional specifications for the detection and alerting system. I mapped the data flows from all source systems to the compliance dashboard, defined alert classification rules with compliance leadership, and designed the regulatory reporting data model to ensure audit trail completeness. I facilitated workshops with compliance officers to validate detection thresholds and alert routing logic, authored the UAT plan with real suspicious pattern scenarios, and coordinated integration with the regulator-facing reporting layer to ensure the system met audit documentation standards.",
    solution: "Requirements-led compliance platform: AML regulation-to-specification translation, data flow mapping across source systems, alert classification definition, regulatory reporting data model design, and structured compliance team UAT before go-live.",
    metrics: [
      "98% detection accuracy on real money laundering cases",
      "$50M+ in suspicious patterns identified",
      "Zero false positives on high-confidence alerts",
      "75% reduction in compliance team review time",
      "Full explainability for regulatory audits",
    ],
    keyLearning: "Compliance officers need to be able to explain every alert to a regulator. The explainability requirement wasn't a nice-to-have — it was the core acceptance criterion. Defining that in the requirements phase shaped the entire system architecture and meant the platform produced reports regulators could act on, not just statistics they had to interpret.",
    techStack: [
      { category: "Compliance", technologies: ["AML", "FINTRAC", "Regulatory Reporting"] },
      { category: "Data", technologies: ["SQL", "SSMS", "Data Profiling", "ETL"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "SharePoint"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD/TDD", "UAT", "Data Modeling"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t2"],
    relatedPhaseSteps: ["01", "02", "06"],
    relatedProjectSlugs: ["kyc-aml-automation", "cloud-security-compliance-automation"],
  },
  {
    id: "10",
    slug: "ecommerce-product-search-recommendations",
    title: "Product Discovery & Search Optimisation",
    tagline: "Lifted product discovery conversion by 35% and average order value by 18% through structured requirements and KPI-driven rollout.",
    role: "Lead Business Systems Analyst — Digital Commerce",
    timeline: "Q1–Q2 2025 · 4 months",
    category: "Digital Commerce + Analytics",
    icon: "🔍",
    accent: "bg-blue-500/15 text-blue-600",
    shortDescription: "Requirements definition and A/B testing framework design for a search and recommendation engine overhaul. Defined KPI taxonomy, validated improvements, and managed phased rollout across a major product catalogue.",
    outcome: "35% conversion lift",
    tags: ["Requirements", "A/B Testing", "Analytics", "SQL", "Agile"],
    coverImage: "/images/projects/ecommerce-product-search-recommendations.jpg",
    coverImageAlt: "Retail shopping bags and ecommerce context suggesting product discovery and recommendations.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "35%", label: "discovery conversion lift" },
      { value: "18%", label: "average order value increase" },
      { value: "28%", label: "lower search bounce rate" },
      { value: "40%", label: "faster time-to-find" },
    ],
    problem: "Traditional keyword search caused high cart abandonment from customers unable to find relevant products. Static rule-based recommendations couldn't personalise to individual behaviour. Business stakeholders had no agreed KPI framework to measure search improvement, making it impossible to validate any change.",
    myRole: "I defined the search and discovery requirements by facilitating workshops with product managers, merchandising teams, and data analysts. I documented current-state search failure modes through data analysis and user research, established a standardized KPI framework across the business, and translated behavioral data patterns into recommendation engine requirements. I designed the A/B testing criteria and acceptance thresholds used to validate each improvement before full rollout, and authored the measurement plan that tracked conversion impact post-launch.",
    solution: "Requirements-led discovery overhaul: stakeholder workshops to define failure modes, KPI taxonomy standardization, technical requirements for search and recommendation engines, A/B test design, and a structured measurement plan for post-launch validation.",
    metrics: [
      "35% lift in product discovery conversion",
      "18% increase in average order value",
      "28% lower search results bounce rate",
      "40% faster time-to-find (3+ min → <2 min)",
      "5M+ search queries daily at sub-100ms latency",
    ],
    keyLearning: "The A/B testing framework was only useful because we defined the success criteria before running tests, not after. Teams that define thresholds post-hoc tend to move the goalposts. Locking in the acceptance criteria in the requirements phase meant every test result was unambiguous.",
    techStack: [
      { category: "Analytics", technologies: ["Power BI", "Tableau", "SQL", "Excel"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "A/B Testing Platforms"] },
      { category: "Integration", technologies: ["RESTful APIs", "Analytics APIs"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD", "UAT", "Data Analysis"] },
    ],
    relatedServiceIds: ["ai-native-ux"],
    relatedPhaseSteps: ["02", "03"],
    relatedProjectSlugs: ["high-performance-ecommerce-checkout"],
  },
  {
    id: "11",
    slug: "high-performance-ecommerce-checkout",
    title: "Checkout Optimisation & Fraud Prevention",
    tagline: "Reduced fraud by 94% and checkout abandonment by 12% simultaneously — with no perceptible impact on legitimate customer experience.",
    role: "Lead Technical Business Analyst — Payments & Compliance",
    timeline: "Q4 2022–Q1 2023 · 5 months",
    category: "Payments + Compliance",
    icon: "💳",
    accent: "bg-orange-500/15 text-orange-600",
    shortDescription: "Requirements mapping and stakeholder alignment for a checkout fraud prevention initiative. Defined fraud detection thresholds, payment gateway integration specifications, and the customer friction tradeoff framework.",
    outcome: "94% fraud reduction",
    tags: ["Payments", "Fraud", "Requirements", "SQL", "Compliance"],
    coverImage: "/images/projects/high-performance-ecommerce-checkout.jpg",
    coverImageAlt: "Contactless payment terminal suggesting fast, secure checkout flows.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "94%", label: "fraud reduction" },
      { value: "$3.8M+", label: "annual fraud savings" },
      { value: "12%", label: "checkout conversion improvement" },
      { value: "<200ms", label: "total checkout latency" },
    ],
    problem: "Dual pressures: significant annual fraud losses and checkout abandonment caused by a slow fraud detection step. The core challenge was defining exactly where to draw the line between fraud prevention and customer friction — a requirements problem before it was a technology problem.",
    myRole: "I mapped the end-to-end checkout flow, identified every fraud decision point and its associated customer friction cost, and facilitated sessions with the fraud, product, and operations teams to define the precision/recall thresholds that balanced security with conversion. I authored the integration specifications for the payment gateway, designed the UAT scenarios used to validate fraud detection accuracy against historical fraud samples, and documented the edge case handling requirements for the async verification path. I also led stakeholder alignment on the risk tolerance framework that governed which orders could be auto-approved versus flagged.",
    solution: "Requirements-led fraud prevention: end-to-end checkout flow mapping, fraud decision point analysis, precision/recall threshold definition with stakeholders, payment gateway integration specifications, and UAT design using historical fraud cases.",
    metrics: [
      "94% fraud reduction ($3.8M+ annual savings)",
      "12% checkout conversion improvement",
      "<200ms total checkout flow",
      "$500M+ annual transaction volume processed",
      "2% false positive rate (industry avg 8-15%)",
    ],
    keyLearning: "The async post-purchase verification path — applying high-friction checks only to genuinely suspicious orders after checkout — was a requirements insight, not a technical one. It only became viable once we had documented the full fraud decision taxonomy and identified which cases could tolerate a post-purchase check versus which needed inline blocking.",
    techStack: [
      { category: "Payments", technologies: ["Payment Gateways", "Tokenization", "Stripe API"] },
      { category: "Data", technologies: ["SQL", "SSMS", "Excel", "Data Analysis"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Visio"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD/TDD", "UAT", "Process Modeling"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedPhaseSteps: ["03", "04"],
    relatedProjectSlugs: ["ecommerce-product-search-recommendations", "landing-page-website"],
  },
  {
    id: "12",
    slug: "distributed-order-fulfillment",
    title: "Supply Chain Visibility & Fulfilment Platform",
    tagline: "Cut average delivery time from 5 days to 2 hours and eliminated overselling entirely — through process reengineering and real-time integration.",
    role: "Lead Business Systems Analyst — Supply Chain",
    timeline: "Q2–Q4 2019 · 8 months",
    category: "Supply Chain + Real-time Systems",
    icon: "📦",
    accent: "bg-green-500/15 text-green-600",
    shortDescription: "End-to-end requirements and process reengineering for a supply chain visibility implementation. Mapped fulfilment workflows across five warehouses, drove stakeholder adoption, and delivered on-schedule go-live.",
    outcome: "2-hour delivery",
    tags: ["Supply Chain", "Process Reengineering", "UML", "SQL", "SaaS Implementation"],
    coverImage: "/images/projects/distributed-order-fulfillment.jpg",
    coverImageAlt: "Stacked shipping boxes suggesting order fulfillment and logistics operations.",
    span: "md:col-span-12",
    minH: "min-h-[240px]",
    impactMetrics: [
      { value: "2h", label: "average delivery (was 3-5 days)" },
      { value: "99.5%", label: "orders fulfilled without cancellation" },
      { value: "25%", label: "lower operational costs" },
      { value: "0", label: "inventory write-offs" },
    ],
    problem: "10,000+ daily orders across five warehouses with 3-5 day delivery, frequent overselling leading to customer cancellations, and significant annual inventory write-offs from manual reconciliation. The operations team needed a single source of truth for inventory status across all warehouse locations.",
    myRole: "I led the requirements gathering and process reengineering for this supply chain visibility implementation at a North American logistics and freight provider. I facilitated workshops with warehouse coordinators, dispatchers, and logistics partners to map the current-state fulfilment workflows, modeled the future state using UML process diagrams, and defined the integration requirements between the visibility platform and the existing inventory systems. I authored the functional and technical specifications, managed stakeholder engagement across the operations team, and designed the UAT plan that validated routing accuracy and inventory sync before go-live. The implementation delivered on schedule — a result driven as much by stakeholder preparation as by technical execution.",
    solution: "Requirements-led visibility implementation: current-state workflow mapping across five warehouses, UML future-state modeling, SaaS integration specifications, logistics partner API requirements, and a structured UAT plan before go-live.",
    metrics: [
      "Average delivery: 3-5 days → 2 hours (same-day in metro areas)",
      "99.5% orders fulfilled without cancellation (zero overselling)",
      "Zero inventory write-offs",
      "10k+ orders per day at 99.9% success rate",
      "25% reduction in operational costs",
    ],
    keyLearning: "Stakeholder buy-in from the warehouse and dispatch teams was harder to earn than any technical integration. Coordinators who had worked manual processes for years needed to see their workflows respected in the design, not overwritten. Running workshops where their input visibly shaped the UML models was what turned skeptics into advocates before a single system went live.",
    techStack: [
      { category: "Platforms", technologies: ["Macro Point", "SaaS Visibility Tools"] },
      { category: "Integration", technologies: ["RESTful APIs", "EDI", "Logistics Partner APIs"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Visio", "Excel"] },
      { category: "Methodology", technologies: ["UML", "Process Reengineering", "BRD", "UAT"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t5"],
    relatedProofMetricTags: ["SaaS implementation"],
    relatedPhaseSteps: ["02", "03", "04"],
    relatedProjectSlugs: ["event-streaming-pipeline"],
  },
  {
    id: "13",
    slug: "real-time-api-attack-detection",
    title: "API Security & Threat Detection Programme",
    tagline: "Slashed attack detection time from 200+ days to under 5 minutes and automated remediation for 94% of incidents.",
    role: "Lead Technical Business Analyst — Security",
    timeline: "Q1–Q2 2024 · 5 months",
    category: "Cybersecurity + Compliance",
    icon: "🛡️",
    accent: "bg-red-500/15 text-red-600",
    shortDescription: "Requirements definition and incident triage workflow design for an API threat detection initiative. Mapped security operations workflows, defined alert classification requirements, and authored the operational runbook.",
    outcome: "98% detection",
    tags: ["Security", "Compliance", "Requirements", "Incident Management", "ITSM"],
    coverImage: "/images/projects/real-time-api-attack-detection.jpg",
    coverImageAlt: "Hands on a laptop keyboard suggesting secure engineering and API threat monitoring.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "98%", label: "attacks detected" },
      { value: "<1s", label: "detection latency" },
      { value: "200d → 5m", label: "median detection time" },
      { value: "94%", label: "incidents auto-remediated" },
    ],
    problem: "Enterprises had no visibility into API attack patterns. Traditional security tools missed sophisticated attacks. The security operations team was drowning in false positives and had no structured incident triage process — which meant real threats were lost in noise.",
    myRole: "I mapped the current-state security operations workflow, identified the gap between raw alert volume and actionable incident intelligence, and documented the functional requirements for the behavioral anomaly detection and triage system. I facilitated workshops with security operations and engineering teams to define alert classification categories and automated remediation boundaries. I authored the incident triage process and operational runbook for the security operations team, ensuring system outputs were actionable for analysts across varying levels of technical depth. I applied ITSM best practices — incident, change, and problem management — throughout the programme design.",
    solution: "Requirements-led security programme: current-state security ops mapping, alert classification definition, automated remediation scope specification, incident triage workflow design, and an ITSM-aligned operational runbook for the security team.",
    metrics: [
      "98% of attack attempts detected",
      "<1 second detection latency",
      "Median detection time: 200+ days → under 5 minutes",
      "87 unique attack patterns identified in first 6 months",
      "94% of attacks auto-remediated before data loss",
      "$2M+ in breach costs prevented",
    ],
    keyLearning: "Security operations teams need actionable outputs, not raw data. The most important requirements work was defining what an 'actionable alert' looked like — what context, what recommended response, what escalation path. Getting that right upstream meant the system produced reports analysts could act on in minutes rather than raw logs they had to interpret for hours.",
    techStack: [
      { category: "Security", technologies: ["ITSM", "SIEM", "Incident Response"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "ServiceNow"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "ITSM", "BRD", "Runbook Design"] },
      { category: "Compliance", technologies: ["Security Frameworks", "Audit Logging", "Change Management"] },
    ],
    relatedPhaseSteps: ["03", "04"],
    relatedServiceIds: ["fractional-leadership"],
    relatedProofMetricTags: ["Change management"],
    relatedProjectSlugs: ["data-breach-forensics-ai", "cloud-security-compliance-automation"],
  },
  {
    id: "14",
    slug: "data-breach-forensics-ai",
    title: "Data Breach Response & Forensic Reporting",
    tagline: "Compressed breach detection from 210 days to 2 hours — with automated regulatory reporting that qualified for GDPR fast-response exemptions.",
    role: "Lead Technical Business Analyst — Security & Compliance",
    timeline: "Q3–Q4 2023 · 5 months",
    category: "Cybersecurity + Compliance",
    icon: "🔎",
    accent: "bg-purple-500/15 text-purple-600",
    shortDescription: "Requirements and regulatory reporting design for a breach forensics platform. Defined data access audit requirements, GDPR/CCPA reporting specifications, and the evidentiary chain documentation for regulatory submissions.",
    outcome: "210 days → 2 hours",
    tags: ["Security", "GDPR", "Compliance", "Audit", "Requirements"],
    coverImage: "/images/projects/data-breach-forensics-ai.jpg",
    coverImageAlt: "Digital security and access concept suggesting breach detection and forensic analysis.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "100×", label: "faster breach detection" },
      { value: "2h", label: "to root cause (was 210 days)" },
      { value: "3×", label: "faster incident response" },
      { value: "100%", label: "root cause identified on all incidents" },
    ],
    problem: "Median breach detection time of 210 days left the organisation exposed to regulatory fines and reputational damage. The forensics process was manual, disconnected, and produced reports that regulators couldn't act on quickly. GDPR and CCPA fast-response exemptions required documented evidence collection within hours, not weeks.",
    myRole: "I led the requirements analysis for the breach forensics platform, mapping current-state breach response workflows and documenting data access audit requirements across all source systems. I defined the GDPR and CCPA regulatory reporting specifications and facilitated compliance team workshops to validate that the automated incident timeline met audit documentation standards. I authored the data lineage documentation required for the evidentiary chain in regulatory submissions and coordinated with the security and legal teams to ensure the platform output qualified for fast-response regulatory exemptions.",
    solution: "Requirements-led forensics platform: breach response workflow mapping, data access audit requirements across source systems, GDPR/CCPA reporting specifications, evidentiary chain documentation design, and compliance team validation workshops.",
    metrics: [
      "Detection time: 210 days → 2 hours (100× improvement)",
      "Root cause identified in 100% of incidents",
      "Full attacker timeline generated automatically",
      "3× faster incident response",
      "Qualified for GDPR/CCPA fast-response exception, reducing fines",
    ],
    keyLearning: "Regulatory reporting requirements need to be defined before the forensics system is designed, not retrofitted after. The evidentiary chain documentation — what data, in what form, with what timestamps, in what chain of custody — determined the entire data architecture. Getting legal and compliance to specify that in the requirements phase was what made the GDPR exemption possible.",
    techStack: [
      { category: "Compliance", technologies: ["GDPR", "CCPA", "Regulatory Reporting", "Audit Logging"] },
      { category: "Security", technologies: ["ITSM", "SIEM", "Incident Response", "Forensics"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "SharePoint"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD", "Data Lineage", "Change Management"] },
    ],
    relatedServiceIds: ["ai-native-ux"],
    relatedPhaseSteps: ["02", "04", "06"],
    relatedProjectSlugs: ["cloud-security-compliance-automation", "real-time-api-attack-detection"],
  },
  {
    id: "15",
    slug: "cloud-security-compliance-automation",
    title: "Cloud Security Posture & Compliance Automation",
    tagline: "Achieved 87% fewer security incidents and continuous SOC2/ISO compliance — reducing audit prep from 40 hours to 2 hours.",
    role: "Lead Technical Business Analyst — Cloud & Compliance",
    timeline: "Q2–Q3 2023 · 5 months",
    category: "Cybersecurity + Compliance",
    icon: "☁️",
    accent: "bg-cyan-500/15 text-cyan-600",
    shortDescription: "Requirements definition and control mapping for a continuous cloud compliance programme. Translated SOC2/ISO 27001 regulatory frameworks into technical policy specifications and automated evidence collection requirements.",
    outcome: "87% fewer incidents",
    tags: ["Cloud", "SOC2", "ISO 27001", "Compliance", "AWS", "Azure"],
    coverImage: "/images/projects/cloud-security-compliance-automation.jpg",
    coverImageAlt: "Abstract technology and connectivity imagery suggesting cloud-scale systems and security posture.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "87%", label: "fewer security incidents" },
      { value: "2h", label: "audit prep (was 40 hours)" },
      { value: "$1.2M+", label: "in compliance fines prevented" },
      { value: "5×", label: "faster cloud deployments" },
    ],
    problem: "Manual cloud security audits ran twice a year, took 40+ hours each, and still missed misconfigurations discovered months later. Regulators increasingly required continuous compliance evidence — not point-in-time snapshots — and the organisation had no process to provide it.",
    myRole: "I led stakeholder engagement across security, engineering, and compliance teams to define the policy requirements and compliance evidence specifications for this continuous monitoring programme. I documented the control mapping from regulatory frameworks (SOC2, ISO 27001) to technical implementation requirements, authored the BRD for the continuous monitoring platform, and designed the automated evidence collection specifications. I also applied ITSM best practices — incident, change, and problem management — throughout the programme and ran change management workshops to help engineering teams understand the policy-as-code governance model and take ownership of their security posture.",
    solution: "Requirements-led compliance programme: regulatory control-to-technical mapping, continuous monitoring BRD, automated evidence collection specifications, ITSM-aligned governance model, and change management programme for engineering adoption.",
    metrics: [
      "87% reduction in security incidents",
      "Continuous SOC2 and ISO 27001 compliance",
      "Audit prep: 40 hours → 2 hours",
      "$1.2M+ in compliance fines prevented",
      "5× faster cloud deployments",
    ],
    keyLearning: "Shifting compliance into the engineering workflow required a cultural change as much as a technical one. The change management programme — helping engineering teams see security policy as their quality gate, not the compliance team's audit — was what drove adoption. Technical automation without that framing would have been worked around.",
    techStack: [
      { category: "Cloud", technologies: ["AWS", "Azure", "Terraform"] },
      { category: "Compliance", technologies: ["SOC2", "ISO 27001", "ITSM", "Policy-as-Code"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "ServiceNow", "SharePoint"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD", "Change Management", "Audit"] },
    ],
    relatedTestimonialIds: ["t4"],
    relatedServiceIds: ["fractional-leadership", "product-design-strategy"],
    relatedProofMetricTags: ["Change management"],
    relatedPhaseSteps: ["04", "05", "06"],
    relatedProjectSlugs: ["real-time-api-attack-detection", "compliance-risk-monitoring"],
  },
  {
    id: "16",
    slug: "landing-page-website",
    title: "Multi-Purpose Landing Page & Marketing Website",
    tagline: "Launched in 3 weeks with a 35% email conversion rate, page-1 keyword ranking in 2 months, and a 98/100 mobile score.",
    role: "Lead Business Systems Analyst — Digital",
    timeline: "Q2 2023 · 3 weeks",
    category: "Web + Digital",
    icon: "🌐",
    accent: "bg-blue-500/15 text-blue-600",
    shortDescription: "End-to-end requirements definition and delivery coordination for a high-converting marketing site. Defined conversion architecture, analytics requirements, and CMS specifications — launched in 3 weeks.",
    outcome: "3-week launch",
    tags: ["Requirements", "Analytics", "SEO", "Stakeholder Management", "Agile"],
    coverImage: "/images/projects/landing-page-website.jpg",
    coverImageAlt: "Laptop showing charts and analytics, suggesting a high-performing marketing site and measurement.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "3 wks", label: "from kick-off to launch" },
      { value: "35%", label: "visitor-to-email conversion" },
      { value: "98/100", label: "mobile performance score" },
      { value: "1.2s", label: "page load time" },
    ],
    problem: "Client needed a professional, high-converting site in weeks, not months, at a fraction of agency cost — without sacrificing performance or SEO quality. Stakeholders had competing priorities and no agreed definition of what 'success' looked like before launch.",
    myRole: "I led end-to-end requirements definition and project coordination for this marketing site build. I facilitated stakeholder workshops to align on conversion goals, SEO targets, and success KPIs before any design work began — resolving competing priorities that would otherwise have caused rework mid-build. I translated business requirements into technical specifications for the development team, managed the analytics stack and A/B testing framework requirements, and documented the CMS operational procedures for the client team's post-launch self-service.",
    solution: "Requirements-first delivery: stakeholder alignment on conversion architecture before design, KPI definition before launch, analytics and A/B testing specifications, and CMS handover documentation for post-launch self-service.",
    metrics: [
      "Launched in 3 weeks (vs 8+ weeks for traditional agency)",
      "1.2 second page load time",
      "35% visitor-to-email conversion rate",
      "Mobile performance score: 98/100",
      "Page 1 keyword ranking within 2 months",
      "Cost: $8k (vs $15k+ agency quote)",
    ],
    keyLearning: "The biggest ROI came from spending the first week on conversion architecture — mapping the user journey and defining CTA placement and success criteria before a single design was produced. Sites that skip the requirements phase to 'move faster' almost always require expensive rework after launch.",
    techStack: [
      { category: "Frontend", technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"] },
      { category: "Analytics", technologies: ["Google Analytics", "Mixpanel", "Hotjar"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Figma"] },
      { category: "Methodology", technologies: ["Agile", "BRD", "UAT", "A/B Testing"] },
    ],
    relatedServiceIds: ["product-design-strategy", "design-systems"],
    relatedPhaseSteps: ["02", "03", "04"],
    relatedProjectSlugs: ["high-performance-ecommerce-checkout"],
  },
  {
    id: "17",
    slug: "hr-management-system",
    title: "HR System Consolidation & Process Automation",
    tagline: "Eliminated 15 hours/week of manual HR data entry and reduced leave approval from 5 days to 1 hour — replacing 3 disconnected tools.",
    role: "Lead Business Systems Analyst — Internal Systems",
    timeline: "Q1–Q2 2023 · 4 months",
    category: "Internal Systems + Automation",
    icon: "👥",
    accent: "bg-green-500/15 text-green-600",
    shortDescription: "Requirements elicitation and process redesign for an HR system consolidation. Mapped three disconnected tools into a unified workflow, managed payroll API integration requirements, and drove user adoption through structured change management.",
    outcome: "3 tools → 1",
    tags: ["HR Systems", "Process Automation", "Requirements", "Change Management", "SQL"],
    coverImage: "/images/projects/hr-management-system.jpg",
    coverImageAlt: "HR management dashboard showing employee records and analytics.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "15h/wk", label: "manual data entry eliminated" },
      { value: "40%", label: "reduction in HR admin overhead" },
      { value: "5 days → 1h", label: "leave approval cycle" },
      { value: "3 → 1", label: "tools consolidated" },
    ],
    problem: "An 80-person company using three disconnected tools with no single source of truth. 15 hours per week lost to manual data entry and error reconciliation. Payroll entries were created days late, causing accounting blind spots and compliance risk.",
    myRole: "I led requirements elicitation across HR, payroll, finance, and management stakeholders for this system consolidation initiative. I documented current-state workflows across three disconnected tools — identifying the integration points, data duplication, and the manual steps creating the 15-hour weekly overhead. I authored the functional specifications for the unified platform, documented payroll API integration requirements for ADP and Gusto, and designed the UAT framework across all HR workflows. I also delivered the change management plan and user training programme that brought the HR team onto the new system with high adoption from week one.",
    solution: "Requirements-led consolidation: current-state workflow mapping across three tools, unified data model specification, payroll API integration requirements, structured UAT, and a change management programme with user training to ensure adoption at go-live.",
    metrics: [
      "15 hours/week of manual data entry eliminated",
      "Leave approval: 5 days → 1 hour",
      "Payroll processing: 2 days → 30 minutes",
      "100% error reduction via single source of truth",
      "40% reduction in HR admin overhead",
    ],
    keyLearning: "The most valuable feature wasn't the one we planned — it was the org chart that managers could see in real time. Once that was in requirements, managers started engaging with the platform for workforce planning, not just record-keeping. Listening carefully in requirements workshops for what stakeholders wished they had — not just what they were asking for — unlocked that scope.",
    techStack: [
      { category: "HR Platforms", technologies: ["ADP", "Gusto", "Payroll Systems"] },
      { category: "Integration", technologies: ["RESTful APIs", "ETL", "SQL"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Visio", "Excel"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD/TDD", "UAT", "Change Management"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t1", "t4"],
    relatedProofMetricTags: ["Platform consolidation", "Change management"],
    relatedPhaseSteps: ["01", "04", "05", "06"],
    relatedProjectSlugs: ["payroll-management-system"],
  },
  {
    id: "18",
    slug: "payroll-management-system",
    title: "Payroll Automation & Accounting Integration",
    tagline: "Cut payroll processing from 40 hours to 20 minutes per month with zero errors — eliminating outsourcing fees and reconciliation delays.",
    role: "Lead Business Systems Analyst — Finance Systems",
    timeline: "Q3–Q4 2022 · 4 months",
    category: "Finance Systems + Automation",
    icon: "💰",
    accent: "bg-yellow-500/15 text-yellow-600",
    shortDescription: "Requirements definition and UAT design for a payroll automation initiative. Identified the five edge cases driving the 8% error rate, documented GL integration specifications, and managed the cutover plan with zero payroll disruption.",
    outcome: "2 days → 20 min",
    tags: ["Payroll", "Accounting", "Requirements", "UAT", "SQL"],
    coverImage: "/images/projects/payroll-management-system.jpg",
    coverImageAlt: "Coins and currency suggesting payroll, compensation, and financial compliance.",
    span: "md:col-span-6",
    minH: "min-h-[260px]",
    impactMetrics: [
      { value: "20 min", label: "payroll processing (was 40h/month)" },
      { value: "0%", label: "error rate (was 8%)" },
      { value: "$3k/mo", label: "outsourcing fees eliminated" },
      { value: "100%", label: "on-time tax filing" },
    ],
    problem: "A 200-person company with manual Excel-based payroll: 8% error rate, 40 hours per month of reconciliation, and GL entries created days late — causing accounting blind spots and compliance risk. The root cause was five recurring edge cases the existing process couldn't model cleanly.",
    myRole: "I led the requirements analysis for this payroll automation initiative, beginning with a structured root cause analysis of the 8% error rate. By mapping the existing manual Excel process in detail, I identified five recurring edge cases — retroactive pay changes, mid-month starts, garnishment order changes, and two others — that accounted for nearly all errors. I documented the functional specifications for automated tax calculation, ACH file generation, and General Ledger integration with QuickBooks, ran UAT with the finance team using the identified edge cases as primary test scenarios, and authored the operational runbook and cutover plan to ensure payroll continuity during the transition.",
    solution: "Requirements-led automation: structured root cause analysis of error patterns, edge case documentation, tax calculation and GL integration specifications, finance team UAT using identified edge cases, and a phased cutover plan with zero payroll disruption.",
    metrics: [
      "Processing time: 40 hours → 20 minutes per month",
      "Error rate: 8% → 0%",
      "$3k/month outsourcing fees eliminated",
      "GL entries created automatically — real-time accounting visibility",
      "100% on-time tax filing, zero audit exceptions",
    ],
    keyLearning: "The 8% error rate wasn't a human failure — it was an information architecture failure. All errors clustered around five edge cases the Excel template couldn't model explicitly. Documenting those edge cases in the requirements phase — rather than leaving them to be discovered in UAT — meant the automated system handled them correctly from day one.",
    techStack: [
      { category: "Finance Systems", technologies: ["QuickBooks", "ADP", "Gusto", "GL Integration"] },
      { category: "Data", technologies: ["SQL", "SSMS", "Excel", "ETL"] },
      { category: "Tools", technologies: ["JIRA", "Confluence", "Visio"] },
      { category: "Methodology", technologies: ["Agile/Scrum", "BRD/TDD", "UAT", "Root Cause Analysis"] },
    ],
    relatedServiceIds: ["product-design-strategy"],
    relatedTestimonialIds: ["t4"],
    relatedProofMetricTags: ["Change management"],
    relatedPhaseSteps: ["04", "05"],
    relatedProjectSlugs: ["hr-management-system"],
  },
]
