// Purpose: Default WeatherSnapshot for unit tests.
import { weatherConditionFromCode } from "./weather-code"
import type { WeatherSnapshot } from "./weather-types"

export function testWeatherSnapshot(overrides: Partial<WeatherSnapshot> = {}): WeatherSnapshot {
  return {
    city: "Place A",
    lat: 43.7,
    lon: -79.4,
    temperatureC: 20,
    weatherCode: 0,
    condition: weatherConditionFromCode(0),
    feelsLikeC: 19,
    wetBulbC: 17,
    humidityPercent: 50,
    windSpeedKmh: 10,
    windDirectionDeg: 180,
    windGustKmh: null,
    dewPointC: null,
    precipitationMm: 0,
    precipitationSumTodayMm: 0,
    cloudCoverPercent: 10,
    pressureHpa: 1015,
    visibilityM: 20000,
    uvIndexMax: 5,
    sunshineDurationSec: 28_800,
    daylightDurationSec: 52_200,
    sunrise: "2026-06-02T06:00",
    sunset: "2026-06-02T20:00",
    todayHighC: 24,
    todayLowC: 14,
    elevationM: 200,
    population: null,
    locationSource: null,
    airQuality: {
      usAqi: 40,
      europeanAqi: 35,
      pm25: 4,
      pm10: 8,
      ozone: 40,
      nitrogenDioxide: 10,
      carbonMonoxide: 200,
      sulphurDioxide: 1,
      label: "Good",
    },
    dailyForecast: [],
    hourlyForecast: [],
    pastWeek: [],
    alerts: [],
    safetyNotices: [],
    marine: null,
    moon: { phaseLabel: "Waxing gibbous", icon: "🌔", illuminationPercent: 75 },
    observedAt: "2026-06-02T14:00",
    timezone: "America/Toronto",
    timezoneAbbreviation: "EDT",
    source: "open-meteo",
    climateNormals: null,
    isDay: true,
    temperatureAnomalyC: null,
    isDefaultLocation: false,
    ...overrides,
  }
}
