import type { Metadata } from "next"

import { PersonaGraph } from "@/components/knowledge-graph/PersonaGraph"

export const metadata: Metadata = {
  title: "Knowledge graph · Charan Pal Deol",
  description:
    "Interactive view of the knowledge graph generated by graphify from the portfolio repository — nodes, edges, and Louvain communities rendered as-is.",
}

export default function KnowledgeGraphPage() {
  return (
    // Escape PortfolioShell padding so the graph fills the viewport below
    // the sticky nav. Data is loaded client-side from /public/knowledge-graph.
    <section className="relative -mx-4 -my-6 h-[calc(100dvh-var(--portfolio-nav-h,72px))] min-h-[620px] md:-mx-6 md:-my-8">
      <PersonaGraph />
    </section>
  )
}
